#! /bin/zsh

# Desktop managment
FIRST_DESK=One
REMAINING_DESKS='Two Three Four Five Six Seven Eight Nine Ten'
bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

# Rules
bspc rule Download floating

# Options
bspc set window_gap 0
bspc set top_padding 16

pgrep -x compton > /dev/null || compton --shadow-exclude '_COMPTON_SHADOW:32c = 0' -bc -t -8 -l -9 -r 6 -o 0.7
