#!/usr/bin/env bash
# Doing the color stuff
xrandr --output HDMI-0 --auto --primary
xrandr --output DVI-1 --auto --right-of HDMI-0

xrdb ~/.Xresources
xrdb -override ~/.dot-yeah/colors/Xresources-gjm

nitrogen --restore &
#mpd &
#~/.dropbox-dist/dropboxd & 

# fonts
xset +fp /usr/share/fonts/local
xset fp rehash

# Fixing pointer
xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:nocaps -layout no

# My beloved urxvtd
urxvtd --quiet --opendisplay --fork

#exec xmonad
exec dwm
