#!/bin/bash

#Xrandr stuff
#xrandr --output DFP5 --auto --primary
#xrandr --output CRT1 --auto --right-of DFP5

# Doing the color stuff
xrdb ~/.Xresources
xrdb -override ~/.dot-yeah/colors/Xresources-tommytiger

nitrogen --restore &
#mpd &
#~/.dropbox-dist/dropboxd & 

# fonts
xset +fp /usr/share/fonts/local
xset fp rehash

setxkbmap -layout no

xbindkeys
#sxhkd & 
exec spectrwm
