#!/usr/bin/env bash
# Doing the color stuff
xrdb ~/.Xresources
xrdb -override ~/.dot-yeah/colors/Xresources-brown

nitrogen --restore &
#mpd &
#~/.dropbox-dist/dropboxd & 

# fonts
xset +fp /usr/share/fonts/local
xset fp rehash

# Fixing pointer
xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:nocaps -layout no

# My beloved urxvtd
urxvtd --quiet --opendisplay --fork

exec xmonad
