# LOADING IN THE DIFFRENT THINGS!

export ZDOTDIR="$HOME"

# Load the first config files.
for config_file ($ZDOTDIR/.zsh/lib/*.zsh); do
  source $config_file
done

autoload -U promptinit && promptinit
autoload -U colors && colors

# Resource files
for file in $ZDOTDIR/.zsh/rc/*.rc; do
  source $file
done

# Plugins
for file in $ZDOTDIR/.zsh/plugins/*; do
  source $file/*.plugin.zsh
done
